# Generated by Django 2.2 on 2019-12-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('game', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=30)),
                ('team2', models.CharField(max_length=30)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('playerpick', models.CharField(max_length=30)),
                ('spread', models.FloatField()),
            ],
        ),
    ]
