# Generated by Django 2.2 on 2019-12-30 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games_new',
            name='Game_ID',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('team_selected', models.CharField(max_length=30)),
                ('total_selected', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picks.games_new')),
            ],
        ),
    ]
