# Generated by Django 2.2 on 2020-01-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_auto_20191230_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='game',
            field=models.CharField(max_length=30),
        ),
    ]
