# Generated by Django 2.2 on 2020-01-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_auto_20200101_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='game',
        ),
    ]
