# Generated by Django 2.2 on 2020-01-02 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0004_remove_choice_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
