# Generated by Django 2.2 on 2020-01-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0005_choice_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='game',
            field=models.CharField(default='', max_length=30),
        ),
    ]
